version: "3.9"
services:
  db:
    image: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: parker
      POSTGRES_USER: peter
  tdd:
    tty: true
    stdin_open: true
    build: .
    container_name: tempotelecom-tdd
    command: >
      bash -c "bundle && \
               bundle exec rake db:create && \
               bundle exec rake db:migrate && \
               echo \"I'm ready. Happy TDDing!\" && \
               sleep infinity"
    volumes:
      - .:/app
      - bundler_gems:/usr/local/bundle
    environment:
      - POSTGRES_PASSWORD=parker
      - POSTGRES_USER=peter
      - RAILS_ENV=test
    depends_on:
      - db
volumes:
  postgres:
  bundler_gems:
